version: '2'

services:
  chrome:
    image: martinsthiago/chrome:64.0.3282.186
    command: "sleep infinity"
    volumes:
      - ../chrome/:/data
    links:
      - web-app
  web-app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    image: testcafe/app
    container_name: web_app
    ports:
      - "9505:9505"
      - "9506:9506"